## Form for rotator settings
table: dc_memory
title: helpers.dc_rotator.settings
controls: design_element_settings

form:
  actions: 
    1: save

  fields:
    10:
      name: delay
      text: helpers.dc_rotator.delay
      help: helpers.dc_rotator.delay_help
      type: text_field
      size: 3
     
    20:
      name: kats
      text: helpers.label.dc_rotator.kats
      help: helpers.help.dc_rotator.kats
      type: select
      multiple: true
      eval: dc_big_table 'rotator'
      css: '#td_record_kats .ms-container {min-width: 250px;}'

    30:
      name: klass
      text: helpers.dc_rotator.klass
      help: helpers.dc_rotator.klass_help
      type: text_field
      size: 20

